[package]
name = "veritasdb"
version = "0.1.0"
authors = ["webb.shi <bradyjoestar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
merklebtree = "0.1.0"
ring = "0.16.9"
hex = "0.4.0"
serde = { version = "1.0.60", features = ["derive"] }
serde_json = "1.0.41"
parking_lot = "0.6.3"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
features = ["sse"]